{{ if eq .Values.plugin "Flannel+Macvlan" }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: network-attachment-definitions.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  scope: Namespaced
  names:
    plural: network-attachment-definitions
    singular: network-attachment-definition
    kind: NetworkAttachmentDefinition
    shortNames:
    - net-attach-def
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                config:
                  type: string
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multus
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multus
subjects:
- kind: ServiceAccount
  name: multus
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus
  namespace: kube-system
---
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: kube-system
  labels:
    tier: node
    app: multus
data:
  cni-conf.json: |
    {
      "name": "multus-cni-network",
      "cniVersion": "0.3.1",
      "type": "multus",
      "capabilities": {
        "portMappings": true
      },
      "delegates": [
        {
          "cniVersion": "0.3.1",
          "name": "default-cni-network",
          "plugins": [
            {
              "type": "flannel",
              "name": "flannel.1",
                "delegate": {
                  "isDefaultGateway": true,
                  "hairpinMode": true
                }
              },
              {
                "type": "portmap",
                "capabilities": {
                  "portMappings": true
                }
              }
          ]
        }
      ],
      "logFile": "/var/log/multus.log",
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
  labels:
    tier: node
    app: multus
    name: multus
spec:
  selector:
    matchLabels:
      name: multus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: multus
        name: multus
      annotations:
        release/revision: "{{ .Release.Revision }}"
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
      serviceAccountName: multus
      containers:
      - name: kube-multus
        image: {{ template "system_default_registry" . }}nfvpe/multus:v3.4.2
        command: ["/entrypoint.sh"]
        args:
        - "--multus-conf-file=/tmp/multus-conf/70-multus.conf"
        - "--cni-version=0.3.1"
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: multus-cfg
          mountPath: /tmp/multus-conf
      volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: multus-cfg
          configMap:
            name: multus-cni-config
            items:
            - key: cni-conf.json
              path: 70-multus.conf
---
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-cni-ds
  namespace: kube-system
  labels:
    tier: node
    app: multus
    name: network-cni-ds
spec:
  selector:
    matchLabels:
      name: network-cni-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: multus
        name: network-cni-ds
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
      serviceAccountName: multus
      containers:
      - name: kube-macvlan-cni
        image: {{ template "system_default_registry" . }}cnrancher/static-macvlan-cni:v0.3.5
        command: ["/entrypoint.sh"]
        args:
        - ""
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
---
# This is a modified Flannel daemonset.
# it is based on: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
# Notably, it removes the creation of an configuration file in/etc/cni/net.d/ 
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flannel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: flannel
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  iface: "{{ .Values.iface }}"
  net-conf.json: |
    {
      "Network": "{{ .Values.podCIDR }}",
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
  namespace: kube-system
  labels:
    tier: node
    app: flannel
    name: flannel
spec:
  selector:
    matchLabels:
      name: flannel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: flannel
        name: flannel
      annotations:
        release/revision: "{{ .Release.Revision }}"
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: flannel
      containers:
      - name: kube-flannel
        image: {{ template "system_default_registry" . }}rancher/coreos-flannel:v0.13.0-rancher1
        command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr" ]
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: FLANNELD_IFACE
          valueFrom:
            configMapKeyRef:
              name: kube-flannel-cfg
              key: iface
        volumeMounts:
        - name: run
          mountPath: /run
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
        - name: run
          hostPath:
            path: /run
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: flannel-cfg
          configMap:
            name: kube-flannel-cfg
---

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  creationTimestamp: null
  name: macvlanips.macvlan.cluster.cattle.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.subnet
    name: Subnet
    type: string
  - JSONPath: .spec.podId
    name: PodId
    type: string
  - JSONPath: .spec.cidr
    name: CIDR
    type: string
  - JSONPath: .spec.mac
    name: MAC
    type: string
  group: macvlan.cluster.cattle.io
  names:
    kind: MacvlanIP
    listKind: MacvlanIPList
    plural: macvlanips
    singular: macvlanip
  scope: Namespaced
  subresources: {}
  validation:
    openAPIV3Schema:
      description: MacvlanIP is a specification for a MacvlanIP resource
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MacvlanIPSpec is the spec for a MacvlanIP resource
          properties:
            cidr:
              type: string
            mac:
              type: string
            podId:
              type: string
            subnet:
              type: string
          required:
          - cidr
          - mac
          - podId
          - subnet
          type: object
      required:
      - spec
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  creationTimestamp: null
  name: macvlansubnets.macvlan.cluster.cattle.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.master
    name: Master
    type: string
  - JSONPath: .spec.vlan
    name: VLAN
    type: string
  - JSONPath: .spec.cidr
    name: CIDR
    type: string
  - JSONPath: .spec.mode
    name: Mode
    type: string
  - JSONPath: .spec.gateway
    name: Gateway
    type: string
  group: macvlan.cluster.cattle.io
  names:
    kind: MacvlanSubnet
    listKind: MacvlanSubnetList
    plural: macvlansubnets
    singular: macvlansubnet
  scope: Namespaced
  subresources: {}
  validation:
    openAPIV3Schema:
      description: MacvlanSubnet is a specification for a MacvlanSubnet resource
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MacvlanSubnetSpec is the spec for a MacvlanSubnet resource
          properties:
            cidr:
              type: string
            gateway:
              type: string
            ipDelayReuse:
              format: int64
              type: integer
            master:
              type: string
            mode:
              type: string
            podDefaultGateway:
              properties:
                enable:
                  type: boolean
                serviceCidr:
                  type: string
              type: object
            ranges:
              items:
                description: IPRange is a list of ip start end range
                properties:
                  rangeEnd:
                    type: string
                  rangeStart:
                    type: string
                required:
                - rangeEnd
                - rangeStart
                type: object
              type: array
            routes:
              items:
                description: Route is route option spec
                properties:
                  dst:
                    type: string
                  gw:
                    type: string
                  iface:
                    type: string
                required:
                - dst
                type: object
              type: array
            vlan:
              type: integer
          required:
          - cidr
          - gateway
          - master
          - mode
          - ranges
          - vlan
          type: object
      required:
      - spec
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-admission-deploy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-admission-deploy
  template:
    metadata:
      labels:
        app: network-admission-deploy
    spec:
      containers:
      - image: {{ template "system_default_registry" . }}cnrancher/network-admission-deploy:v0.6.2-rc1
        name: network-admission-deploy
      serviceAccountName: multus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-controller
  namespace: kube-system
  labels:
    app: network-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-controller
  template:
    metadata:
      namespace: kube-system
      labels:
        app: network-controller
    spec:
      serviceAccountName: multus
      containers:
      - image: {{ template "system_default_registry" . }}cnrancher/network-controller:v0.6.2-rc1
        name: network-controller
        resources:
          limits:
            memory: "256Mi"
        volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
      volumes:
        - name: webhook-certs
          secret:
            secretName: network-controller-webhook-certs
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-net-attach-def-controller
  namespace: kube-system
  labels:
    app: kube-net-attach-def-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-net-attach-def-controller
  template:
    metadata:
      namespace: kube-system
      labels:
        app: kube-net-attach-def-controller
    spec:
      serviceAccountName: multus
      containers:
      - image: {{ template "system_default_registry" . }}cnrancher/k8s-net-attach-def-controller:v0.1.2
        name: kube-net-attach-def-controller
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "k8s-net-attach-def-controller --logtostderr 10;" ]
---
{{ end }}
